"""
DistillToMCU — Dashboard 数据生成器
===================================
从正式分析结果生成 poc/dashboard_data.js，仪表盘优先加载真实数据：
  - 6 组实验的每日 metrics + 规则快照
  - 8 基线 × 6 数据集的 AR / 决策一致性（baseline_results.json）
  - Friedman / Nemenyi 统计结果（statistics_results.json）
  - 5 组消融（含 held-out 泛化，seed42/ablation_results.json）

用法：python generate_dashboard_data.py
输出：poc/dashboard_data.js
"""

import json
import os


OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")

# (数据目录, 仪表盘 key, 显示名)
EXPERIMENTS = [
    # (exp_dir, dashboard_key, label, baseline_key)
    ("run4b_seed42_seed42",  "seed42",  "Seed 42 (Synthetic 4x)", "synthetic_seed42"),
    ("run4b_seed123_seed42", "seed123", "Seed 123 (Synthetic 4x)", "synthetic_seed123"),
    ("run4b_seed999_seed42", "seed999", "Seed 999 (Synthetic 4x)", "synthetic_seed999"),
    ("run4b_seed777_seed42", "seed777", "Seed 777 (Synthetic 4x)", "synthetic_seed777"),
    ("run4b_strands_seed42", "strands", "STRANDS Aruba-1 (4x)",     "strands_aruba1"),
    ("run4b_uci_seed42",     "uci_v3",  "UCI V3 (Real Sensors 4x)", "uci_v3"),
]


def load_json(path):
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_metrics(exp_dir):
    path = os.path.join(OUTPUT_DIR, exp_dir, "metrics.jsonl")
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(l) for l in f if l.strip()]


def load_rules(exp_dir):
    data = load_json(os.path.join(OUTPUT_DIR, exp_dir, "rules_snapshot.json"))
    return data or []


def main():
    experiments = {}
    for exp_dir, key, label, bl_key in EXPERIMENTS:
        if not os.path.exists(os.path.join(OUTPUT_DIR, exp_dir, "metrics.jsonl")):
            print(f"[SKIP] {exp_dir} missing, excluding from dashboard data.")
            continue
        experiments[key] = {
            "label": label,
            "metrics": load_metrics(exp_dir),
            "rules": load_rules(exp_dir),
        }

    baselines = load_json(os.path.join(OUTPUT_DIR, "baseline_results_4x.json")) or {}
    stats = load_json(os.path.join(OUTPUT_DIR, "statistics_4x_baselines.json")) or {}
    ablations = (load_json(os.path.join(OUTPUT_DIR, "ablation_results_4x.json"))
                 or load_json(os.path.join(OUTPUT_DIR, "seed42",
                                           "ablation_results.json")) or {})

    # 基线：每个数据集 → 按名字排好的 {ar, agree, ccr, display_name}
    baselines_by_exp = {}
    baseline_names = stats.get("baselines") or []
    for exp_dir, key, label, bl_key in EXPERIMENTS:
        if key not in experiments:
            continue
        # v10.6: baseline_results_4x.json 以"数据集_种子"为键，取 seed-42 代表行
        bl4 = bl_key
        if bl_key.startswith("synthetic_"):
            bl4 = bl_key + "_s42"
        elif bl_key == "strands_aruba1":
            bl4 = "strands_s42"
        elif bl_key == "uci_v3":
            bl4 = "uci_v3_s42"
        entry = baselines.get(bl4, {})
        rows = []
        for name in baseline_names:
            b = entry.get("baselines", {}).get(name, {})
            rows.append({
                "name": name.replace("B1 ", "").replace("B2 ", "").replace("B3 ", "")
                           .replace("B4 ", "").replace("B5 ", "").replace("B6 ", "")
                           .replace("B7 ", "").replace("B8 ", ""),
                "ar": b.get("autonomy_rate", 0),
                "agree": b.get("decision_agreement_pct", 0),
                "ccr": b.get("cloud_call_reduction", 0),
                "display": b.get("display_name", name),
            })
        baselines_by_exp[key] = rows

    # 统计摘要（供仪表盘展示）
    stats_summary = None
    if stats:
        fa = stats.get("friedman_ar", {})
        na = stats.get("nemenyi_ar", {})
        sig_pairs = [p for p in na.get("pairs", []) if p.get("significant")]
        stats_summary = {
            "friedman_chi2": fa.get("chi2"),
            "friedman_p": fa.get("p_value"),
            "nemenyi_cd": na.get("critical_difference"),
            "significant_pairs": len(sig_pairs),
            "n_datasets": stats.get("datasets", []),
        }

    # 消融（seed42）
    ab = {}
    if ablations:
        ab = {
            "sources": ablations.get("1_distillation_sources", {}),
            "generalization": ablations.get("2_rule_generalization", {}),
            "lifecycle": ablations.get("3_rule_lifecycle", {}),
            "bandit": ablations.get("4_pms_vs_alternatives", {}),
            "flash": ablations.get("5_flash_strategy", {}),
        }

    payload = {
        "experiments": experiments,
        "baselines_by_exp": baselines_by_exp,
        "statistics": stats_summary,
        "ablations": ab,
        "cost_per_call_cny": 0.0007,
    }

    js = "/* Auto-generated by generate_dashboard_data.py — do not edit. */\n"
    js += "var DASH_DATA = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n"
    out_path = os.path.join(os.path.dirname(__file__), "dashboard_data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {out_path} ({len(js)/1024:.1f} KB)")
    print(f"  experiments: {len(experiments)}, baselines rows: "
          f"{sum(len(v) for v in baselines_by_exp.values())}, stats: {stats_summary is not None}")


if __name__ == "__main__":
    main()
